# Generated by Django 4.2.4 on 2023-08-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
